/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author Gabriel-PC
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnHab = new javax.swing.JSpinner();
        spnPoder = new javax.swing.JSpinner();
        spnEsp = new javax.swing.JSpinner();
        sliEstagio = new javax.swing.JSlider();
        pnlAtrBasico = new javax.swing.JPanel();
        lblRes = new javax.swing.JLabel();
        lblControle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFor = new javax.swing.JLabel();
        lblAgi = new javax.swing.JLabel();
        pnlCombate = new javax.swing.JPanel();
        lblDef = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblAcc = new javax.swing.JLabel();
        lblasd = new javax.swing.JLabel();
        lblAccEn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblEstagio = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblEnergia = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblPP = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblPC = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbRaca = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        lblPDL = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mighty Strike - Dragon Ball");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(204, 204, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(670, 558));

        spnHab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spnHab.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        spnHab.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        spnHab.setFocusable(false);
        spnHab.setName("Poder"); // NOI18N
        spnHab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnHabStateChanged(evt);
            }
        });

        spnPoder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spnPoder.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        spnPoder.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        spnPoder.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spnPoder.setDoubleBuffered(true);
        spnPoder.setFocusable(false);
        spnPoder.setName("Poder"); // NOI18N
        spnPoder.setOpaque(false);
        spnPoder.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnPoderStateChanged(evt);
            }
        });

        spnEsp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spnEsp.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        spnEsp.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        spnEsp.setFocusable(false);
        spnEsp.setName("Poder"); // NOI18N
        spnEsp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnEspStateChanged(evt);
            }
        });

        sliEstagio.setMaximum(5);
        sliEstagio.setMinimum(1);
        sliEstagio.setOrientation(javax.swing.JSlider.VERTICAL);
        sliEstagio.setValue(1);
        sliEstagio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliEstagioStateChanged(evt);
            }
        });

        pnlAtrBasico.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Atributos Básicos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        pnlAtrBasico.setForeground(new java.awt.Color(255, 255, 255));

        lblRes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRes.setText("0");

        lblControle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblControle.setText("0");

        jLabel1.setText("Força");

        jLabel2.setText("Reflexos");

        jLabel3.setText("Resistência");

        jLabel4.setText("Controle de Ki");

        lblFor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFor.setText("0");

        lblAgi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgi.setText("0");

        javax.swing.GroupLayout pnlAtrBasicoLayout = new javax.swing.GroupLayout(pnlAtrBasico);
        pnlAtrBasico.setLayout(pnlAtrBasicoLayout);
        pnlAtrBasicoLayout.setHorizontalGroup(
            pnlAtrBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAtrBasicoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAtrBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(pnlAtrBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAtrBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblControle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlAtrBasicoLayout.setVerticalGroup(
            pnlAtrBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtrBasicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAtrBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblFor))
                .addGap(6, 6, 6)
                .addGroup(pnlAtrBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblAgi))
                .addGap(6, 6, 6)
                .addGroup(pnlAtrBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblRes))
                .addGap(6, 6, 6)
                .addGroup(pnlAtrBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblControle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCombate.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Combate", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        pnlCombate.setForeground(new java.awt.Color(255, 255, 255));

        lblDef.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDef.setText("0");

        jLabel9.setText("Acerto (Fis)");

        jLabel10.setText("Defesa");

        lblAcc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAcc.setText("0");

        lblasd.setText("Acerto (En)");

        lblAccEn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccEn.setText("0");

        javax.swing.GroupLayout pnlCombateLayout = new javax.swing.GroupLayout(pnlCombate);
        pnlCombate.setLayout(pnlCombateLayout);
        pnlCombateLayout.setHorizontalGroup(
            pnlCombateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCombateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCombateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblasd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(pnlCombateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAcc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDef, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAccEn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pnlCombateLayout.setVerticalGroup(
            pnlCombateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCombateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCombateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDef, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCombateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcc)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCombateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblasd)
                    .addComponent(lblAccEn))
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Microgramma D Extended", 0, 24)); // NOI18N
        jLabel6.setText("Habilidade");

        jLabel7.setFont(new java.awt.Font("Microgramma D Extended", 0, 24)); // NOI18N
        jLabel7.setText("Poder");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Estágio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        lblEstagio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEstagio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstagio.setText("1");
        lblEstagio.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEstagio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblEstagio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Energia", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        lblEnergia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEnergia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnergia.setText("0");
        lblEnergia.setToolTipText("(Poder+Espírito+Habilidade) x 5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PPs", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        lblPP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPP.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPP, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblPP, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PCs", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        lblPC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPC.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblPC, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Microgramma D Extended", 0, 24)); // NOI18N
        jLabel11.setText("Espírito");

        cmbRaca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbRaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ", "Humano", "Saiya-jin", "1/2 Saiya-jin", "Namekusei-jin", "Changeling" }));
        cmbRaca.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cmbRaca.setFocusable(false);
        cmbRaca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbRacaItemStateChanged(evt);
            }
        });
        cmbRaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRacaActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Poder de Luta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP), "Poder de Luta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jPanel5.setDoubleBuffered(false);
        jPanel5.setFocusable(false);

        lblPDL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPDL, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPDL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Mighty Strike.png"))); // NOI18N
        lblImagem.setDoubleBuffered(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnPoder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel7)))
                            .addComponent(cmbRaca, 0, 219, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlAtrBasico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlCombate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliEstagio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnPoder, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnHab, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pnlAtrBasico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pnlCombate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(sliEstagio, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    void pp() { // retorna pontos de personagem
        int r = cmbRaca.getSelectedIndex();
        int est = sliEstagio.getValue();
        int p = (int) spnPoder.getValue();
        int e = (int) spnEsp.getValue();
        int h = (int) spnHab.getValue();
        
        int pp = 0;      
        if (r==0 && est>=1) {
            pp = p+e+h+((est-1)*20);    
        }
        if (est>=1 && r !=0) {
            pp = p+e+h-3+((est-1)*20);
        }
        lblPP.setText(Integer.toString(pp));    
    }
    
    void pdl() { // retorna poder de luta
        int fo = Integer.parseInt(lblFor.getText());
        int agi = Integer.parseInt(lblAgi.getText());
        int res = Integer.parseInt(lblRes.getText());
        int ctl = Integer.parseInt(lblControle.getText());
        int ene = Integer.parseInt(lblEnergia.getText());
        int est = sliEstagio.getValue();
        int pp = Integer.parseInt(lblPP.getText());
        int estpdl = (int) Math.pow(10, est);
        lblPDL.setText(Integer.toString(((fo+agi+res+ctl+pp)*est)*estpdl+(ene*estpdl)));
    }
    
    private void spnPoderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnPoderStateChanged
        int est = sliEstagio.getValue();
        int p = (int) spnPoder.getValue();
        int e = (int) spnEsp.getValue();
        int h = (int) spnHab.getValue();
        
        lblEnergia.setText(Integer.toString(p * 5 + e * 5 + h * 5)); // Energia = (Poder+Habilidade+Espírito)*5

        // Atributos Básicos
        lblFor.setText(Integer.toString((p + e) / 2)); // Força = ( Poder + Espírito ) / 2
        lblRes.setText(Integer.toString(p / 2 + ((e + h) / 4))); // Resistência = Poder / 2 + ((Espírito+Habilidade)/4)
        lblAgi.setText(Integer.toString(h / 2 + ((p + e) / 4))); // Agilidade = Habilidade / 2 + ( Espírito + Poder ) / 4 )
        lblControle.setText(Integer.toString((e + h) / 2)); // Controle = ( Espírito + Habilidade ) / 2

        // Combate
        lblAcc.setText(Integer.toString((p + h) / 2));
        lblAccEn.setText(Integer.toString((e + h) / 2));
        lblDef.setText(Integer.toString(h / 2 + ((p + e) / 4)));
        
        pp(); // procedimento gera pontos de personagem
        
        pdl(); // procedimento gera poder de luta


    }//GEN-LAST:event_spnPoderStateChanged

    private void spnHabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnHabStateChanged
        int est = sliEstagio.getValue();
        int p = (int) spnPoder.getValue();
        int e = (int) spnEsp.getValue();
        int h = (int) spnHab.getValue();
        
        lblEnergia.setText(Integer.toString(p * 5 + e * 5 + h * 5)); // Energia = (Poder+Habilidade+Espírito)*5

        // Atributos Básicos
        lblFor.setText(Integer.toString((p + e) / 2)); // Força = ( Poder + Espírito ) / 2
        lblRes.setText(Integer.toString(p / 2 + ((e + h) / 4))); // Resistência = Poder / 2 + ((Espírito+Habilidade)/4)
        lblAgi.setText(Integer.toString(h / 2 + ((p + e) / 4))); // Agilidade = Habilidade / 2 + ( Espírito + Poder ) / 4 )
        lblControle.setText(Integer.toString((e + h) / 2)); // Controle = ( Espírito + Habilidade ) / 2

        // Combate
        lblAcc.setText(Integer.toString((p + h) / 2));
        lblAccEn.setText(Integer.toString((e + h) / 2));
        lblDef.setText(Integer.toString(h / 2 + ((p + e) / 4)));
        
        pp(); // procedimento gera pontos de personagem
        
        pdl(); // procedimento gera poder de luta


    }//GEN-LAST:event_spnHabStateChanged

    private void spnEspStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnEspStateChanged
        int est = sliEstagio.getValue();
        int p = (int) spnPoder.getValue();
        int e = (int) spnEsp.getValue();
        int h = (int) spnHab.getValue();
        
        lblEnergia.setText(Integer.toString(p * 5 + e * 5 + h * 5)); // Energia = (Poder+Habilidade+Espírito)*5

        // Atributos Básicos
        lblFor.setText(Integer.toString((p + e) / 2)); // Força = ( Poder + Espírito ) / 2
        lblRes.setText(Integer.toString(p / 2 + ((e + h) / 4))); // Resistência = Poder / 2 + ((Espírito+Habilidade)/4)
        lblAgi.setText(Integer.toString(h / 2 + ((p + e) / 4))); // Agilidade = Habilidade / 2 + ( Espírito + Poder ) / 4 )
        lblControle.setText(Integer.toString((e + h) / 2)); // Controle = ( Espírito + Habilidade ) / 2

        // Combate
        lblAcc.setText(Integer.toString((p + h) / 2));
        lblAccEn.setText(Integer.toString((e + h) / 2));
        lblDef.setText(Integer.toString(h / 2 + ((p + e) / 4)));
        
        pp(); // procedimento gera pontos de personagem
        
        pdl(); // procedimento gera poder de luta

    }//GEN-LAST:event_spnEspStateChanged

    private void sliEstagioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliEstagioStateChanged
        int est = sliEstagio.getValue();
        int p = (int) spnPoder.getValue();
        int e = (int) spnEsp.getValue();
        int h = (int) spnHab.getValue();
        
        lblEstagio.setText(Integer.toString(est));
        
        pp(); // procedimento gera pontos de personagem
        
        pdl(); // procedimento gera poder de luta
    }//GEN-LAST:event_sliEstagioStateChanged

    private void cmbRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRacaActionPerformed

    }//GEN-LAST:event_cmbRacaActionPerformed

    private void cmbRacaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbRacaItemStateChanged
        int est = sliEstagio.getValue();
        int p = (int) spnPoder.getValue();
        int e = (int) spnEsp.getValue();
        int h = (int) spnHab.getValue();
        int r = cmbRaca.getSelectedIndex();
        switch (r) {
            case 1:
                spnHab.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
                spnPoder.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
                spnEsp.setModel(new javax.swing.SpinnerNumberModel(2, 2, 10, 1));
                break;
            case 2:
                spnPoder.setModel(new javax.swing.SpinnerNumberModel(2, 2, 10, 1));
                spnEsp.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
                spnHab.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
                break;
            case 3:
                spnPoder.setModel(new javax.swing.SpinnerNumberModel(2, 2, 10, 1));
                spnHab.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
                spnEsp.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
                break;
            case 4:
                spnHab.setModel(new javax.swing.SpinnerNumberModel(2, 2, 10, 1));
                spnEsp.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
                spnPoder.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
                break;
            case 5:
                spnPoder.setModel(new javax.swing.SpinnerNumberModel(3, 3, 10, 1));
                spnHab.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
                spnEsp.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
                break;
            default:
                spnHab.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
                spnPoder.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
                spnEsp.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
                break;
        }
        lblEnergia.setText(Integer.toString(p * 5 + e * 5 + h * 5)); // Energia = (Poder+Habilidade+Espírito)*5

        // Atributos Básicos
        lblFor.setText(Integer.toString((p + e) / 2)); // Força = ( Poder + Espírito ) / 2
        lblRes.setText(Integer.toString(p / 2 + ((e + h) / 4))); // Resistência = Poder / 2 + ((Espírito+Habilidade)/4)
        lblAgi.setText(Integer.toString(h / 2 + ((p + e) / 4))); // Agilidade = Habilidade / 2 + ( Espírito + Poder ) / 4 )
        lblControle.setText(Integer.toString((e + h) / 2)); // Controle = ( Espírito + Habilidade ) / 2

        // Combate
        lblAcc.setText(Integer.toString((p + h) / 2));
        lblAccEn.setText(Integer.toString((e + h) / 2));
        lblDef.setText(Integer.toString(h / 2 + ((p + e) / 4)));
        
        pp(); // procedimento gera pontos de personagem
        
        pdl(); // procedimento gera poder de luta
    }//GEN-LAST:event_cmbRacaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbRaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblAcc;
    private javax.swing.JLabel lblAccEn;
    private javax.swing.JLabel lblAgi;
    private javax.swing.JLabel lblControle;
    private javax.swing.JLabel lblDef;
    private javax.swing.JLabel lblEnergia;
    private javax.swing.JLabel lblEstagio;
    private javax.swing.JLabel lblFor;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblPC;
    private javax.swing.JLabel lblPDL;
    private javax.swing.JLabel lblPP;
    private javax.swing.JLabel lblRes;
    private javax.swing.JLabel lblasd;
    private javax.swing.JPanel pnlAtrBasico;
    private javax.swing.JPanel pnlCombate;
    private javax.swing.JSlider sliEstagio;
    private javax.swing.JSpinner spnEsp;
    private javax.swing.JSpinner spnHab;
    private javax.swing.JSpinner spnPoder;
    // End of variables declaration//GEN-END:variables
}
